# Generated by Django 6.1.1 on 2026-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Philosopher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Faylasufning ismi')),
                ('slug', models.SlugField(blank=True, help_text="Bo'sh qoldirilsa, ismdan avtomatik shakllantiriladi.", max_length=220, unique=True, verbose_name='Slug (havola uchun)')),
                ('era', models.CharField(blank=True, help_text="Masalan: Antik davr, Sharq Renessansi, Ratsionalizm, Ma'rifatparvarlik...", max_length=150, verbose_name='Davri / Falsafiy oqimi')),
                ('birth_death_years', models.CharField(blank=True, help_text='Masalan: Mil. avv. 470 - 399 yoki 980 - 1037', max_length=100, verbose_name='Yashagan yillari')),
                ('image', models.ImageField(blank=True, null=True, upload_to='philosophers/', verbose_name='Faylasuf rasmi')),
                ('short_description', models.CharField(blank=True, help_text="Ro'yxatda ko'rinadigan qisqacha ma'lumot", max_length=400, verbose_name="Qisqacha ta'rif")),
                ('biography', models.TextField(verbose_name="Batafsil ma'lumot (Tarjimai hol va faoliyati)")),
                ('main_ideas', models.TextField(blank=True, verbose_name="Asosiy falsafiy g'oyalari va ta'limoti")),
                ('famous_quotes', models.TextField(blank=True, help_text='Har bir iqtibosni yangi qatordan yozishingiz mumkin.', verbose_name='Mashhur iqtiboslari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi tahrir')),
            ],
            options={
                'verbose_name': 'Faylasuf',
                'verbose_name_plural': 'Faylasuflar',
                'ordering': ['name'],
            },
        ),
    ]
