# Generated by Django 6.1.1 on 2026-09-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philosophers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philosopher',
            name='era',
            field=models.CharField(blank=True, db_index=True, help_text="Masalan: Antik davr, Sharq Renessansi, Ratsionalizm, Ma'rifatparvarlik...", max_length=150, verbose_name='Davri / Falsafiy oqimi'),
        ),
        migrations.AlterField(
            model_name='philosopher',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Faylasufning ismi'),
        ),
        migrations.AddIndex(
            model_name='philosopher',
            index=models.Index(fields=['name'], name='philosopher_name_cfc38a_idx'),
        ),
        migrations.AddIndex(
            model_name='philosopher',
            index=models.Index(fields=['era'], name='philosopher_era_74aa79_idx'),
        ),
    ]
