# Generated by Django 6.1.1 on 2026-09-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philosophers', '0002_alter_philosopher_era_alter_philosopher_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('order', models.PositiveIntegerField(default=1, help_text='Masalan: 1 dan 10 gacha', verbose_name='Savol tartibi')),
                ('explanation', models.TextField(blank=True, help_text="Foydalanuvchi javob berganidan keyin ko'rsatiladigan ma'lumot", verbose_name='Javob izohi / tushuntirish')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Test 1, Test 2: Antik davr falsafasi...', max_length=200, verbose_name="Test to'plami nomi")),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug (havola uchun)')),
                ('description', models.TextField(blank=True, help_text='Ushbu test qaysi mavzularni qamrab olgani haqida qisqa tushuntirish.', verbose_name="Test haqida qisqacha ma'lumot")),
                ('order', models.PositiveIntegerField(default=1, help_text='Chiqish tartibi (1, 2, 3...)', verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="Belgilansa, saytda foydalanuvchilarga ko'rinadi.", verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "Test to'plami",
                'verbose_name_plural': "Test to'plamlari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Javob varianti')),
                ('is_correct', models.BooleanField(default=False, help_text="Ushbu variant to'g'ri bo'lsa belgilang", verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='philosophers.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='philosophers.quiz', verbose_name="Tegishli test to'plami"),
        ),
    ]
