# Generated by Django 6.0.6 on 2026-09-30 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philosophers', '0003_question_quiz_choice_question_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name="To'g'ri javoblar soni")),
                ('total_questions', models.PositiveIntegerField(verbose_name='Jami savollar soni')),
                ('percentage', models.PositiveIntegerField(verbose_name="Foiz ko'rsatkichi")),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Batafsil javoblar tahlili')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Yechilgan sana va vaqt')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='philosophers.quiz', verbose_name="Test to'plami")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-completed_at'],
            },
        ),
    ]
