# Generated by Django 6.0.6 on 2026-10-02 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philosophers', '0004_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aphorism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Aforizm matni')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name="Saytda ko'rsatilsinmi?")),
                ('order', models.PositiveIntegerField(default=0, help_text="Kichik raqam yuqorida ko'rinadi.", verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('philosopher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aphorisms', to='philosophers.philosopher', verbose_name='Faylasuf')),
            ],
            options={
                'verbose_name': 'Aforizm',
                'verbose_name_plural': 'Aforizmlar',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['philosopher', 'is_published'], name='philosopher_philoso_3ee697_idx')],
            },
        ),
    ]
