# Generated by Django 6.1.1 on 2026-10-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philosophers', '0005_aphorism'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_mega',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Belgilansa, bu test testlar sahifasida alohida 'Mega Test' bloki sifatida ko'rinadi.",
                verbose_name='Umumlashtiruvchi mega-testmi?'
            ),
        ),
    ]
